name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy FastAPI App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}  # IP address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }}    # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }}  # User of the server you want to ssh into
          script: |
            mkdir -p test-project
            cd test-project
            git clone github.com/saumyaranjan2003/fastapi-deploy.git || true
            cd fastapi-deploy
            git checkout main && git pull origin main
            sudo docker compose -f docker-compose.yml up --build -d
            sudo docker image prune -f
            echo 'Deployment successful!'
